---
version: "3.9"
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:0.12.6
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=ap-northeast-1
